apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ .Values.passwd | sha256sum }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        name: {{ template "fullname" . }}
        ports:
        - containerPort: 8883
          name: "mqtt"

        volumeMounts:
          - name: tls-ca
            mountPath: /mosquitto/tls-ca
            readOnly: true
          - name: tls-server
            mountPath: /mosquitto/tls-server
            readOnly: true
          - name: mosquitto-conf
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
            readOnly: true
          - name: passwd
            mountPath: /etc/mosquitto/passwd
            subPath: passwd
            readOnly: true
          - name: mosquitto-data
            mountPath: /mosquitto/data
            subPath: mosquitto/data
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: tls-ca
        secret:
          secretName: {{ template "fullname" . }}-ca
      - name: tls-server
        secret:
          secretName: {{ template "fullname" . }}-tls
      - name: mosquitto-conf
        configMap:
          name: {{ template "fullname" . }}
      - name: passwd
        configMap:
          name: mqtt-passwd
      - name: mosquitto-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
