# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: smizy/mosquitto:1.4.12-alpine

imagePullPolicy: IfNotPresent

ingress:
  enabled: false

service:
  enabled: true
  type: LoadBalancer

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: standard
  
resources:
  requests:
    cpu: 50m
    memory: 100Mi

config: |-
  log_dest stdout
  listener 8883
  password_file /etc/mosquitto/passwd
  allow_anonymous false
  cafile /mosquitto/tls-ca/ca.crt
  certfile /mosquitto/tls-server/tls.crt
  keyfile /mosquitto/tls-server/tls.key

passwd: |-
  admin:$6$CugH57SaJ4bXB5Ui$jHWGbmIw1XmBCe9aIAbZHD7O45YeLbKOCAE4dTWz6LxT1yiek6CVcpMiJd3YUbVvfEo4ScpqT9JT60wLFN3vQA==
